### PR TITLE
Support Python3

### PR DESCRIPTION
**Pull request by ClemPi**
Code bytes http response.
Handle urllib refactor.

Address #2

### CODE REVIEW

**Comment by valerytschopp** [comment]
Hi ClemPi,
For the urllib refactor, wouldn't it be better to do something like this:
```python
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
```
instead of explicitly checking the python version?

**Comment by ClemPi** [comment]
I did this because the method is not the same and we have to explicitly check the version when calling `urlencode` : https://github.com/valerytschopp/python-radosgw-admin/pull/4/commits/566adf64a0bae09c967109703153a11a2c13dc38#diff-fe3c0a5df953368eb825f1815aa2b8c9R99.
But we can do the other way if you prefer

**Comment by valerytschopp** [comment]
Yes, I understand. 
Sorry my example was bad, I really would prefer:
```python
try:
    from urllib.parse import urlencode
except ImportError:
    from urllib import urlencode

...
      urlencode(query_params)
...
```

**Comment by ClemPi** [comment]
Yes, better alternative.
Just updated the PR

**Pull request merged**
